//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoVenta.PRESENTACION
{
    public partial class frmFactura
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblNumeroVenta;
        protected global::System.Web.UI.WebControls.Label lblFecha;
        protected global::System.Web.UI.WebControls.Label lblCliente;
        protected global::System.Web.UI.WebControls.Label lblTelefono;
        protected global::System.Web.UI.WebControls.Label lblDireccion;
        protected global::System.Web.UI.WebControls.GridView gvDetalle;
        protected global::System.Web.UI.WebControls.Label lblEstado;
        protected global::System.Web.UI.WebControls.Label lblMetodoPago;
        protected global::System.Web.UI.WebControls.Panel pnlPayPal;
        protected global::System.Web.UI.WebControls.Label lblPayPalID;
        protected global::System.Web.UI.WebControls.Label lblSubtotal;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Panel pnlObservaciones;
        protected global::System.Web.UI.WebControls.Label lblObservaciones;
    }
}
