//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoVenta.PRESENTACION
{
    public partial class frmVenta
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox txtNumeroVenta;
        protected global::System.Web.UI.WebControls.TextBox txtFecha;
        protected global::System.Web.UI.WebControls.TextBox txtCliente;
        protected global::System.Web.UI.WebControls.Button btnBuscarCliente;
        protected global::System.Web.UI.WebControls.HiddenField hfIdCliente;
        protected global::System.Web.UI.WebControls.TextBox txtDireccionEntrega;
        protected global::System.Web.UI.WebControls.Label lblSubtotal;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.HiddenField hfPagoAprobado;
        protected global::System.Web.UI.WebControls.HiddenField hfPayPalOrderID;
        protected global::System.Web.UI.WebControls.DropDownList ddlProducto;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divTipo;
        protected global::System.Web.UI.WebControls.DropDownList ddlTipo;
        protected global::System.Web.UI.WebControls.TextBox txtCantidad;
        protected global::System.Web.UI.WebControls.TextBox txtPrecioUnit;
        protected global::System.Web.UI.WebControls.Button btnAgregar;
        protected global::System.Web.UI.WebControls.TextBox txtNotas;
        protected global::System.Web.UI.WebControls.GridView gvDetalle;
        protected global::System.Web.UI.WebControls.TextBox txtObservaciones;
        protected global::System.Web.UI.WebControls.Button btnNuevo;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.TextBox txtBuscarCliente;
        protected global::System.Web.UI.WebControls.Button btnFiltrarCliente;
        protected global::System.Web.UI.WebControls.GridView gvClientes;
        protected global::System.Web.UI.WebControls.HiddenField hfLatitud;
        protected global::System.Web.UI.WebControls.HiddenField hfLongitud;
        protected global::System.Web.UI.WebControls.HiddenField hfDireccionMapa;
    }
}
